# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-12 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('emp_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1)),
                ('dateofJoining', models.CharField(max_length=1000)),
                ('birthDate', models.CharField(max_length=1000)),
                ('currentCCT', models.IntegerField()),
                ('totalVOCScore', models.IntegerField()),
                ('vocScoresForLast2months', models.CharField(max_length=1000)),
                ('total_Calls', models.IntegerField()),
                ('auxOutTimeHrs', models.FloatField()),
                ('qcal_Score', models.IntegerField()),
                ('avgCCTForLast7Days', models.CharField(max_length=1000)),
                ('schedule_Hrs', models.FloatField()),
                ('sales_Audit_Verification_Percent', models.IntegerField()),
                ('staffed_Hrs', models.FloatField()),
                ('fcr_Rate', models.IntegerField()),
                ('sales_Coverted', models.IntegerField()),
                ('cctRanking', models.FloatField()),
                ('aux_Exception_Hrs', models.FloatField()),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
