# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-12 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.IntegerField()),
                ('qual_score', models.IntegerField()),
                ('os', models.IntegerField()),
                ('fcr', models.IntegerField()),
                ('sav', models.IntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.user_profile')),
            ],
        ),
    ]
