# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='birthDate',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='dateofJoining',
            field=models.CharField(max_length=1000),
        ),
    ]
