# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-12 11:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0002_betting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingBets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.CharField(max_length=20, null=True)),
                ('cct_bet', models.CharField(max_length=20, null=True)),
                ('qual_score', models.CharField(max_length=20, null=True)),
                ('qual_score_bet', models.CharField(max_length=20, null=True)),
                ('os', models.CharField(max_length=20, null=True)),
                ('os_bet', models.CharField(max_length=20, null=True)),
                ('fcr', models.CharField(max_length=20, null=True)),
                ('fcr_bet', models.CharField(max_length=20, null=True)),
                ('sav', models.CharField(max_length=20, null=True)),
                ('sav_bet', models.CharField(max_length=20, null=True)),
                ('total_bet', models.CharField(max_length=20, null=True)),
                ('total_win', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.IntegerField(blank=True, default=0, null=True)),
                ('qual_score', models.IntegerField(blank=True, default=0, null=True)),
                ('os', models.IntegerField(blank=True, default=0, null=True)),
                ('fcr', models.IntegerField(blank=True, default=0, null=True)),
                ('sav', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('team_cct', models.IntegerField()),
                ('team_os', models.IntegerField()),
                ('team_fcr', models.IntegerField()),
                ('tema_sav', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.Team')),
            ],
        ),
        migrations.CreateModel(
            name='UserJson',
            fields=[
                ('emp_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1)),
                ('dateofJoining', models.CharField(max_length=1000)),
                ('birthDate', models.CharField(max_length=1000)),
                ('currentCCT', models.IntegerField()),
                ('totalVOCScore', models.IntegerField()),
                ('vocScoresForLast2months', models.CharField(max_length=1000)),
                ('total_Calls', models.IntegerField()),
                ('auxOutTimeHrs', models.FloatField()),
                ('qcal_Score', models.IntegerField()),
                ('avgCCTForLast7Days', models.CharField(max_length=1000)),
                ('schedule_Hrs', models.FloatField()),
                ('sales_Audit_Verification_Percent', models.IntegerField()),
                ('staffed_Hrs', models.FloatField()),
                ('fcr_Rate', models.IntegerField()),
                ('sales_Coverted', models.IntegerField()),
                ('cctRanking', models.FloatField()),
                ('aux_Exception_Hrs', models.FloatField()),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('emp_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1)),
                ('dateofJoining', models.CharField(max_length=1000)),
                ('birthDate', models.CharField(max_length=1000)),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('level_points', models.IntegerField(blank=True, default=0, null=True)),
                ('betting_points', models.IntegerField(blank=True, default=1000, null=True)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='betting',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user_detail',
        ),
        migrations.DeleteModel(
            name='Betting',
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.UserProfile'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.UserProfile'),
        ),
        migrations.AddField(
            model_name='level',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_level', to='gamification.UserProfile'),
        ),
        migrations.AddField(
            model_name='bettingbets',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.UserProfile'),
        ),
    ]
